
name: jd_crazy_joy crazyJoy任务
 
on:
  workflow_dispatch:
  schedule:
     - cron: '10 18 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        JDJOY_SHARECODES: ${{ secrets.JDJOY_SHARECODES }}
        JDJOY_HELPSELF: ${{ secrets.JDJOY_HELPSELF }}
        JDJOY_APPLYJDBEAN: ${{ secrets.JDJOY_APPLYJDBEAN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: 运行 【crazyJoy任务】
        if: env.JD_COOKIE
        run: |
          node jd_crazy_joy.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY || github.event.client_payload.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH || github.event.client_payload.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND || github.event.client_payload.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN || github.event.client_payload.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET || github.event.client_payload.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY || github.event.client_payload.IGOT_PUSH_KEY }}
